version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports: ["27017:27017"]
    environment: { MONGO_INITDB_DATABASE: demo }
    volumes: [ "./mongo/init:/docker-entrypoint-initdb.d:ro" ]

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes: [ "./postgres/init:/docker-entrypoint-initdb.d:ro" ]
